### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_column_letter'

### ISSUE THREAD

**Issue by Colelyman** [BYUCS260/TA-Resources#1]
Hey @jnielson94, I tried running the [parseEvals.py](https://github.com/BYUCS260/TA-Resources/blob/master/parseEvals.py) script and got the following error:

> You've either reached the end or have an error!
Traceback (most recent call last):
  File "parseEvals.py", line 114, in <module>
    Letter = openpyxl.cell.get_column_letter(y)
AttributeError: 'module' object has no attribute 'get_column_letter'

Any ideas why this would happen? I am using `python-2.7` and `openpyxl-2.4.8`.

**Comment by jnielson94** [comment]
openpyxl-2.3.5 should work. I know openpyxl-2.4.x won't work since they did some major changes to how you access data. I did get that on my mac when I tried to run it, but couldn't figure out what happened (and haven't had time with the STEM fair and such to dig into it).

**Comment by jnielson94** [comment]
I re-ran `pip install -r requirements.txt` and it turns out that it didn't have the right openpyxl version. @Colelyman could you try that and let me know if that fixes it?

**Comment by Colelyman** [comment]
I just tried it and everything was successful! Thanks Jordan.
